# Lab 5 (Nhập môn): Làm quen với PyTorch

Bài thực hành này là bước đệm để bạn làm quen với PyTorch, một trong những thư viện Deep Learning mạnh mẽ và phổ biến nhất.

## 1. Mục tiêu
* Hiểu và thao tác với đối tượng quan trọng nhất trong PyTorch: Tensor.
* Hiểu cách PyTorch tự động tính toán đạo hàm (gradient) thông qua autograd.
* Biết cách xây dựng một mạng nơ-ron đơn giản bằng cách kế thừa lớp `torch.nn.Module`.
* Làm quen với hai lớp (layer) cơ bản: `nn.Linear` và `nn.Embedding`.

## 2. Các bước thực hiện

### Import thư viện cần thiết

In [1]:
import torch
import numpy as np

### Phần 1: Khám phá Tensor

Tensor là cấu trúc dữ liệu cốt lõi của PyTorch, tương tự như ndarray của NumPy nhưng có thêm khả năng chạy trên GPU và tự động tính đạo hàm.

#### Task 1.1: Tạo Tensor

In [2]:
# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n{x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n{x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
tensor([[1, 2],
        [3, 4]])

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.8223, 0.8870],
        [0.7349, 0.2153]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


#### Task 1.2: Các phép toán trên Tensor

In [3]:
print("\n--- Task 1.2: Các phép toán trên Tensor ---")
add_result = x_data + x_data
print(f"x_data + x_data:\n{add_result}\n")

mul_result = x_data * 5
print(f"x_data * 5:\n{mul_result}\n")

matmul_result = x_data @ x_data.T
print(f"x_data @ x_data.T:\n{matmul_result}\n")


--- Task 1.2: Các phép toán trên Tensor ---
x_data + x_data:
tensor([[2, 4],
        [6, 8]])

x_data * 5:
tensor([[ 5, 10],
        [15, 20]])

x_data @ x_data.T:
tensor([[ 5, 11],
        [11, 25]])



#### Task 1.3: Indexing và Slicing

In [4]:
print("\n--- Task 1.3: Indexing và Slicing ---")
first_row = x_data[0]
print(f"Hàng đầu tiên: {first_row}")

second_col = x_data[:, 1]
print(f"Cột thứ hai: {second_col}")

value = x_data[1, 1]
print(f"Giá trị (hàng 2, cột 2): {value}\n")


--- Task 1.3: Indexing và Slicing ---
Hàng đầu tiên: tensor([1, 2])
Cột thứ hai: tensor([2, 4])
Giá trị (hàng 2, cột 2): 4



#### Task 1.4: Thay đổi hình dạng Tensor

In [5]:
print("\n--- Task 1.4: Thay đổi hình dạng Tensor ---")
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor (4, 4) ban đầu:\n{tensor_4x4}\n")

tensor_16x1 = tensor_4x4.view(16, 1)
print(f"Tensor (16, 1) sau khi reshape/view:\n{tensor_16x1}\n")
print(f"Shape mới: {tensor_16x1.shape}")


--- Task 1.4: Thay đổi hình dạng Tensor ---
Tensor (4, 4) ban đầu:
tensor([[0.9972, 0.3188, 0.2187, 0.0058],
        [0.8132, 0.1623, 0.4040, 0.9158],
        [0.8190, 0.1269, 0.4425, 0.2901],
        [0.8056, 0.5954, 0.1822, 0.1696]])

Tensor (16, 1) sau khi reshape/view:
tensor([[0.9972],
        [0.3188],
        [0.2187],
        [0.0058],
        [0.8132],
        [0.1623],
        [0.4040],
        [0.9158],
        [0.8190],
        [0.1269],
        [0.4425],
        [0.2901],
        [0.8056],
        [0.5954],
        [0.1822],
        [0.1696]])

Shape mới: torch.Size([16, 1])


### Phần 2: Tự động tính Đạo hàm với autograd

In [6]:
print("\n--- Task 2.1: Thực hành với autograd ---")
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"grad_fn của y: {y.grad_fn}")

z = y * y * 3
print(f"z: {z}")

z.backward()
print(f"Đạo hàm của z theo x (dz/dx): {x.grad}")


--- Task 2.1: Thực hành với autograd ---
x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x0000012BD719B7F0>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x (dz/dx): tensor([18.])


In [7]:
print("\n--- Thử gọi backward() lần 2 ---")
try:
    z.backward()
except RuntimeError as e:
    print(f"Lỗi khi gọi backward() lần 2: {e}")


--- Thử gọi backward() lần 2 ---
Lỗi khi gọi backward() lần 2: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.


### Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

In [8]:
print("\n--- Task 3.1: Lớp nn.Linear ---")
linear_layer = torch.nn.Linear(in_features=5, out_features=2)
input_tensor = torch.randn(3, 5)
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")


--- Task 3.1: Lớp nn.Linear ---
Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
tensor([[-0.4417,  0.6662],
        [ 0.1794,  1.6721],
        [-1.2578,  0.6438]], grad_fn=<AddmmBackward0>)


In [9]:
print("\n--- Task 3.2: Lớp nn.Embedding ---")
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)
input_indices = torch.LongTensor([1, 5, 0, 8])
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n{embeddings}")


--- Task 3.2: Lớp nn.Embedding ---
Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
tensor([[-0.4954, -1.4475, -0.7673],
        [ 0.2882, -1.1867,  0.5738],
        [ 0.3952,  1.0548, -1.0349],
        [-0.1952, -1.2946, -1.3610]], grad_fn=<EmbeddingBackward0>)


In [10]:
print("\n--- Task 3.3: Kết hợp thành một nn.Module ---")
from torch import nn

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
print("Đã khởi tạo mô hình:")
print(model)

input_data = torch.LongTensor([[1, 2, 5, 9]])
print(f"\nInput data shape: {input_data.shape}")

output_data = model(input_data)
print(f"Model output shape: {output_data.shape}")
print(f"Model output data:\n{output_data}")


--- Task 3.3: Kết hợp thành một nn.Module ---
Đã khởi tạo mô hình:
MyFirstModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (activation): ReLU()
  (output_layer): Linear(in_features=8, out_features=2, bias=True)
)

Input data shape: torch.Size([1, 4])
Model output shape: torch.Size([1, 4, 2])
Model output data:
tensor([[[-0.6115,  0.0753],
         [-0.3643,  0.2336],
         [-0.6416, -0.0710],
         [-0.3912,  0.2651]]], grad_fn=<ViewBackward0>)


## 3. Kết luận

Qua bài lab này, bạn đã làm quen với các thành phần cơ bản nhất của PyTorch: Tensor, autograd, và cách định nghĩa mô hình bằng nn.Module.